index:
    path: /
    controller: App\Controller\CurrencyController::index

edit:
    path: /edit
    controller: App\Controller\CurrencyController::edit
    methods: POST

rateList:
    path: /list
    controller: App\Controller\CurrencyController::rateList

addRate:
    path: /add
    controller: App\Controller\CurrencyController::addRate

delRate:
    path: /delete
    controller: App\Controller\CurrencyController::delRate

addCurrency:
    path: /add_currency
    controller: App\Controller\CurrencyController::addCurrency

addCoin:
    path: /add_coin
    controller: App\Controller\CurrencyController::addCoin

delCoin:
    path: /delete_coin
    controller: App\Controller\CurrencyController::delCoin