index:
    path: /
    controller: App\Controller\CurrencyController::index

edit:
    path: /edit
    controller: App\Controller\CurrencyController::edit
    methods: POST

rateList:
    path: /list
    controller: App\Controller\CurrencyController::rateList

addRate:
    path: /add_rate
    controller: App\Controller\CurrencyController::addRate

delRate:
    path: /delete_rate
    controller: App\Controller\CurrencyController::delRate

currency:
    path: /currency
    controller: App\Controller\CurrencyController::currency

addCurrency:
    path: /add_currency
    controller: App\Controller\CurrencyController::addCurrency

delCurrency:
    path: /delete_currency
    controller: App\Controller\CurrencyController::delCurrency